// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
// Prisma 7 no longer auto-loads .env files, so load it ourselves before env() resolves.
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
